---
- name: Old Istio Identifier
  become: true
  find:
    paths: /opt/kubernetes
    pattern: "istio-\\d+\\.\\d+\\.\\d+$"
    recurse: no
    file_type: directory
    use_regex: yes
    excludes: "istio-{{ istio_version }}"
  register: istio_old_installations

- name: Delete Old Istio Installations
  become: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ istio_old_installations.files }}"
  when: istio_old_installations.matched != 0

